### ISSUE TITLE
Show built store paths

### ISSUE THREAD

**Issue by jluttine** [Mic92/nixpkgs-review#102]
After running `nixpkgs-review` for a pull request, I'd like to test that the executables are working. For this, I'd need to know which store paths nixpkgs-review built. So, it'd be nice if at the end of the review, nixpkgs-review would show all store paths it needed to build. Then I could go through them one by one and see if they contain any executables I'd like to test.

Now I can see this:

```
1 package built:
rssguard
```

But as it doesn't have the store path, I'm not able to find it.

Does this make sense? I'm just trying to figure out a good way to test executables that are affected by a pull request.

**Comment by Mic92** [comment]
We do that for packages that have an attribute.
Once you are in the `nix-shell` you can look in the current directory in `results`. Is this sufficient for your use case?

```
[nix-shell:~/.cache/nixpkgs-review/pr-86391-1]$ ls -la results/
total 4
drwxr-xr-x 2 joerg users  3 May  4 16:21 .
drwxr-xr-x 5 joerg users  8 May  4 16:21 ..
lrwxrwxrwx 1 joerg users 61 May  4 16:21 gpio-utils -> /nix/store/q36q5a4mdhgwijznl2l0y25jkljb24dv-gpio-utils-5.4.38
```

**Comment by jluttine** [comment]
Ah, that sounds perfect! Thanks! :+1: 

I wonder if it would make sense to print this piece of information when nixpkgs-review finishes the review? Something like `Built packages can be found under results/`.

Anyway, this solves my usecase.

**Comment by Mic92** [comment]
I could add some documentation of data files generated by `nixpkgs-review`. However I want to limit the printed output of the tool for readability.

**Comment by jluttine** [comment]
Maybe to `nixpkgs-review --help`?

**Comment by jluttine** [comment]
Well, you know what's the best place. Thanks for the response and solution!

**Comment by jluttine** [comment]
Hmm, `man` page for `nixpkgs-review` might be a really nice place for all such information. I'm always using only `--help`, `man` and `info`, not looking at any online documentation unless need to find some really comprehensive information. I just love good man pages. :grin:

**Comment by Mic92** [comment]
I suppose sphinx has manpage support?

**Comment by jluttine** [comment]
Oh, so it seems: `make man`. I didn't realise this was written in Python, but I wasn't aware that Sphinx can generate man pages either. But apparently it can, interesting!
