### ISSUE TITLE
Github API access token scopes

### ISSUE THREAD

**Issue by DamienCassou** [Mic92/nixpkgs-review#104]
Hi,

what are the scopes one has to activate for a github API token to work with nixpkgs-review?

I get an error message with the scopes I picked:

> urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by Mic92** [comment]
Good questions. I would say something like `repo` -> `public_repo`? I have not tried it thoroughly though.
Currently nixpkgs-review posts pull requests comments, approves pull requests and merge them. It also uses the token to get information from public repositories.

**Comment by priegger** [comment]
For posting pull request comments, public_repo is enough.

**Comment by Mic92** [comment]
Does this answers the question?

**Comment by priegger** [comment]
It makes sense to add this information to the readme. Could you test if public_repo is enough for the approve and merge functionality? I can create a PR for the documentation, but I cannot test the merge part on nixpkgs.

**Comment by Pamplemousse** [comment]
According to [the documentation](https://docs.github.com/en/developers/apps/scopes-for-oauth-apps#available-scopes), here is what the **public_repo** scope allows:
> Limits access to  public repositories. That includes read/write access to code, commit  statuses, repository projects, collaborators, and deployment statuses  for public repositories and organizations. Also required for starring  public repositories.

My interpretation of "includes read/write access to code" is that it implies merging PR.
(although, I could not find anywhere -in their doc or the internet- any confirmation of that...)

**Comment by davidak** [comment]
I can confirm that repo:public_repo  is enough to post comment.
It would be good to have this information in the readme.
