### ISSUE TITLE
Add PR creation

### ISSUE THREAD

**Issue by blaggacao** [Mic92/nixpkgs-review#115]
Out of discussion: https://github.com/NixOS/nixpkgs/pull/92612#discussion_r451192710

On a power-user workflow (which avoids leaves the command line end-to-end),
it would make sense to combine two things of tow different authoritative origin
in the first PR message:

- Origin 1: GithubTemplate per contribution type (new pkg, new module, pkg update, module update)
- Origin 2: Preliminary results of local nipkgxs-review session

Supersedes #114 #113 

/cc @jtojnar uses `gh` to avoid leaving the command line, but it's not trivial to _combine_ PR template and local input from `./result.md` (correct me if I'm wrong)

ANother argument is automating PR with query parameters, see: https://docs.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters

**Comment by Mic92** [comment]
Does this work for you?

```
$ hub pull-request -m "$(cat .github/PULL_REQUEST_TEMPLATE.md)" -m "$(nix-review wip)"
```

**Comment by blaggacao** [comment]
Sounds perfect!

**Comment by Mic92** [comment]
I would rather add this feature to nix-update: https://github.com/Mic92/nix-update/
It already supports nixpkgs-review feature.
