### ISSUE TITLE
Common test for (go) packages

### ISSUE THREAD

**Issue by blaggacao** [Mic92/nixpkgs-review#120]
wrong 
```console
k3d --version
k3d version 3.0.0
k3s version v1.18.6-k3s1 (default)
```
vs goo

```console
k3d --version
k3d version 3-dev
k3s version v1.18.4-k3s1 (default)
```

by overlooking wrong

```nix
''
...
        -X github.com/rancher/k3d/version.Version=${version}
        -X github.com/rancher/k3d/version.K3sVersion=v${k3sVersion}
...
''
```
vs good
```nix
''
...
        -X github.com/rancher/k3d/v3/version.Version=${version}
        -X github.com/rancher/k3d/v3/version.K3sVersion=v${k3sVersion}
...
''
```
a common pattern in go version bumps when bumping major versions.

Derived from #117 

Further inspiration (not sure, how fit): https://github.com/GoogleContainerTools/container-structure-test#command-tests

**Comment by Mic92** [comment]
I have no idea how this relates to nixpkgs-review?

**Comment by Mic92** [comment]
If you want some sort of linting than https://github.com/jtojnar/nixpkgs-hammering is maybe the better place for it.

**Comment by blaggacao** [comment]
Hm, I also don't remember the context properly 😂. Mayeb it was about a common --version test or so. But I guess the general discussion where tests should be specified determined it should generally not be this tool, but probably a test attribute.
