### ISSUE TITLE
Not much seems to have happen, and report is meager

### ISSUE THREAD

**Issue by Pamplemousse** [Mic92/nixpkgs-review#122]
I am not too familiar with `nixpkgs-review`, so maybe I have wrong expectations here...

Wanting to review nixos/nixpkgs#68524, I obtain the following:

```shell
[nix-shell:~/Workspace/tools/nixpkgs]$ nix-review pr 68524
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/68524/head:refs/nixpkgs-review/1
$ git worktree add /home/pamplemousse/.cache/nixpkgs-review/pr-68524/nixpkgs 6127d1e117dfb7c85f216435f3a4378368b2966a
Preparing worktree (detached HEAD 6127d1e117d)
Updating files: 100% (22433/22433), done.
HEAD is now at 6127d1e117d Merge pull request #95261 from r-ryantm/auto-update/operator-sdk
$ nix-env -f /home/pamplemousse/.cache/nixpkgs-review/pr-68524/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit 01058f5099b92e48d4bccba8639a8b7a7d3b4cb0
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 3864 and retry the command.
Automatic merge went well; stopped before committing as requested
$ nix-env -f /home/pamplemousse/.cache/nixpkgs-review/pr-68524/nixpkgs -qaP --xml --out-path --show-trace --meta
Nothing changed
https://github.com/NixOS/nixpkgs/pull/68524
$ nix-shell /home/pamplemousse/.cache/nixpkgs-review/pr-68524/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-68524]$ cat report.md 
Result of `nixpkgs-review pr 68524` [1](https://github.com/Mic92/nixpkgs-review)
```

It appears that `fetchRepoProject` is used by [`amdvlk`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/amdvlk/default.nix), so I expected the report to show at least this package being built...

Is there a bug? Did I overlook anything (the `warning`s)? Was I expecting the wrong behavior?

Thanks for you help :slightly_smiling_face:

**Comment by Pamplemousse** [comment]
I checked out the PR, which has not been rebased in a while, and there is no package importing `fetchRepoProject`.
So, I guess that `nix-review` did not see anything to build...

Might be nice to have a message like "Nothing to be built.".

**Comment by Mic92** [comment]
makes sense.

**Comment by Mic92** [comment]
`amdvlk` is not rebuild because `fetchRepoProject` is a fixed-input derivation with a checksum.
When the checksum stays the same, nix won't rebuilt it. Hence nixpkgs-review is not able to detect changes.
