### ISSUE TITLE
ignoring 'sandbox' because you are not a trusted user

### ISSUE THREAD

**Issue by 06kellyjac** [Mic92/nixpkgs-review#133]
I'm a new `nixpkgs-review` user and when running it against a PR I got the following warning:
`warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user`

Is this warning showing up because sandbox is already enabled globally on nixos or have I just screwed something up? :sweat_smile: 

---

`nix-shell -p nix-info --run "nix-info -m"`
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.10, NixOS, 21.03pre244416.daaa0e33505 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager, nixos-21.03pre244416.daaa0e33505, nixos-hardware"`
 - channels(jk): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Mic92** [comment]
nix-review tries to enable sandboxing unconditionally - which is something only user marked as 'trusted' in nix.conf can do.. However since you are on NixOS this is already the case unless you disabled it, in which case you would knew. Hence it is safe to ignore this warning.

**Comment by 06kellyjac** [comment]
Awesome, thanks
