### ISSUE TITLE
Arrange for nixpkgs-reviewed label with ofborg

### ISSUE THREAD

**Issue by blaggacao** [Mic92/nixpkgs-review#137]
If ofborg detects a not so secret sentinel markdown comment applied not so secretively on the fly by nixpkgs whem commenting on issues, it should apply corresponding label such as:

`nixpkgs-reviewed`, which indicates confidence of having passed a nixpkgs-review run without failure.

https://discourse.nixos.org/t/how-many-people-are-paid-to-work-on-nix-nixpkgs/8307/73?u=blaggacao

**Comment by Mic92** [comment]
What does nixpkgs-review needs to for this?

**Comment by blaggacao** [comment]
@Mic92 I don't know. Maybe just a supportive stance and a motion from you.

But almost more importantly, I have no clarity what actions or decision need to be taken (also from others) to make this happen. Do you?

One thing that comes to my mind though: How would ofborg tell it's `nixpkgs-review` on the phone?

**Comment by Mic92** [comment]
Maybe rather than ofborg this could be handled by @timokau's marvin-mk2 bot? https://github.com/timokau/marvin-mk2 It also feels like a better fit since it deal with review statuses.

**Comment by blaggacao** [comment]
I like the idea, and agree! Although marvin still has to proof it's effectiveness, this vould be a valuable addition.

For the text matching, nixpkgs-review could expose hidden hints in the style of:
`<!-- nixpkgs-review-status: ok -->`

**Comment by timokau** [comment]
I'm a bit hesitant. marvin-mk2 is very experimental, its not yet certain if it will stick around. I would like to keep its scope well defined, especially since I don't have enough time to put into it as-is.

I would say I'm open to contributions, but its hard to test changes on the bot if you don't have it set up (a testing instance on something like heroku).

**Comment by blaggacao** [comment]
Oh thank you @timokau for this assessment. Looking ahead, how does ofborg politics work, then? Must this go through an RFC?

**Comment by Mic92** [comment]
@blaggacao no you contribute to ofborg directly or use its issue tracker.

**Comment by blaggacao** [comment]
Done so in: https://github.com/NixOS/ofborg/issues/534

**Comment by Mic92** [comment]
@rmcgibbo 's nixpkgs-review bot could add flags. but I am not really sure we would need those. It's obvious if someone run nixpkgs-review, when looking at the pr.
