### ISSUE TITLE
Include architecture in report.md

### ISSUE THREAD

**Issue by SuperSandro2000** [Mic92/nixpkgs-review#139]
I am currently reviewing/fixing a lot of packages for Darwin. It would be handy if bit and architecture would be mentioned by default in the report.md. 

Example:
```
Result of nixpkgs-review run on darwin x84_64
```

```
Result of nixpkgs-review run on NixOS i386
```

This is similar to #129

**Comment by Mic92** [comment]
Yes. Makes perfect sense to have it.
