### ISSUE TITLE
Support rebuilding more than 1024 packages

### ISSUE THREAD

**Issue by zimbatm** [Mic92/nixpkgs-review#140]
For example, when I was rebuilding https://github.com/NixOS/nixpkgs/pull/101655, at the end of the build I got a few pages of errors like this:
```
bash: /nix/store/ny7vshs45d5k193ql3b51dak0hjwwqc2-findutils-4.7.0/bin/find: Argument list too long
bash: /nix/store/7fdm1ij6f7xwjmhpici1bh3xh08n0sp7-coreutils-8.31/bin/basename: Argument list too long
bash: /nix/store/4crjhnvd8yhk063r7pwxpw6kd8aq0rbv-gnugrep-3.5/bin/grep: Argument list too long
bash: /nix/store/7fdm1ij6f7xwjmhpici1bh3xh08n0sp7-coreutils-8.31/bin/basename: Argument list too long
bash: /nix/store/4crjhnvd8yhk063r7pwxpw6kd8aq0rbv-gnugrep-3.5/bin/grep: Argument list too long
bash: /nix/store/7fdm1ij6f7xwjmhpici1bh3xh08n0sp7-coreutils-8.31/bin/basename: Argument list too long
bash: /nix/store/7fdm1ij6f7xwjmhpici1bh3xh08n0sp7-coreutils-8.31/bin/basename: Argument list too long
bash: /nix/store/7fdm1ij6f7xwjmhpici1bh3xh08n0sp7-coreutils-8.31/bin/basename: Argument list too long
bash: /nix/store/7fdm1ij6f7xwjmhpici1bh3xh08n0sp7-coreutils-8.31/bin/basename: Argument list too long
bash: /nix/store/7fdm1ij6f7xwjmhpici1bh3xh08n0sp7-coreutils-8.31/bin/basename: Argument list too long
bash: /nix/store/7fdm1ij6f7xwjmhpici1bh3xh08n0sp7-coreutils-8.31/bin/basename: Argument list too long
```

I suspect that the derivations are passed as arguments, which exceeds the Linux max argument size of 1024.

**Comment by zimbatm** [comment]
```
[nix-shell:~/.../nixpkgs-review/pr-101655-4]$ nixpkgs-review --version
bash: /nix/store/dwkkfkkxlbpcvxy37b2mvg300qhhp48i-nixpkgs-review-2.4.2/bin/nixpkgs-review: Argument list too long
```

**Comment by Mic92** [comment]
Increase your stack size :). Just kidding this is not the [nix](https://github.com/NixOS/nix/issues/2147) issue tracker. I suppose this restriction build inputs in nix-shell? Because nixpkgs-review generates a file for the package list.

**Comment by Mic92** [comment]
It might be actually environment variables instead of argv. Both are stored on the stack.

**Comment by SuperSandro2000** [comment]
Encountered this bug while building https://github.com/NixOS/nixpkgs/pull/105427 which only tries to build 24 packages.

**Comment by Mic92** [comment]
These are operating systems limitations. I cannot solve this in nixpkgs-review really.

**Comment by lordcirth** [comment]
> These are operating systems limitations. I cannot solve this in nixpkgs-review really.

Can you have it accept a file containing the names, rather than listing them all in argv?

**Comment by zimbatm** [comment]
I think that it's possible to split the work chunks of 1k elements, but it will require quite a bit of refactoring.

**Comment by Mic92** [comment]
> I think that it's possible to split the work chunks of 1k elements, but it will require quite a bit of refactoring.

I think the exact number is a bit fussy though. It depends on how many environment numbers can be loaded together into one nix shell.

**Comment by Mic92** [comment]
This is solved in https://github.com/Mic92/nixpkgs-review/pull/162
