### ISSUE TITLE
Report if python packages ran 0 tests

### ISSUE THREAD

**Issue by SuperSandro2000** [Mic92/nixpkgs-review#144]
Python packages sometimes do not contain the tests and report ``Ran 0 tests in 0.000s``. I think it would a good measure to include that in the report.py so that people can properly fix this.

**Comment by jonringer** [comment]
I don't think toolchain specific filter would scale very well. Especially python where standards are frequently subject to change

short term fix is to do `nix log -f ./nixpkgs ./results/<pkg-name>` and you'll be able to see the output

**Comment by SuperSandro2000** [comment]
I want to automate this to easily catch this without thinking about it. I could detect nixpkgs-review with several ENVs like GIT_{AUTHOR,COMMITER}_{NAME,EMAIL} and then put a little rg script in my .bashrc which warns me about this.

**Comment by jonringer** [comment]
This doesn't really fix the review problem. But pytest will fail if 0 tests are ran. So packages with `pytestCheckHook` will only work if tests are ran.

**Comment by SuperSandro2000** [comment]
I hacked the following together:

```
nixpkgs-review-lint() {
  if [[ $GIT_AUTHOR_NAME == nixpkgs-review ]]; then
    (rg --colors "match:bg:yellow" --colors "match:fg:magenta" 'Ran 0 tests in 0.000s' &)
  fi
}

PROMPT_COMMAND="${PROMPT_COMMAND:+${PROMPT_COMMAND};}nixpkgs-review-lint"
```

Requires rg (ripgrep) and bash.

**Comment by jonringer** [comment]
the `results` directory in nixpkgs-review will be symlinks to a bunch of nix store paths, you could also do something like:
```bash
check_tests() {
    for store_path in ./results/*; do
        if nix log $store_path | grep 'Ran 0 tests in 0.000s'; then
            // packages were rebuilt which don't have tests
        fi
    done
}
```
this unfortunately will also trigger if a rebuild also didn't have tests

**Comment by Mic92** [comment]
There is also `~/.cache/nixpkgs-review/pr-<NUM>/logs` that have the logs.

**Comment by SuperSandro2000** [comment]
This is what I currently use:

```shell
nixpkgs-review-lint() {
  if [[ $GIT_AUTHOR_NAME == nixpkgs-review && -z $NIXPKGS_REVIEW_LINT_RUN ]]; then
    (
      cd logs/ || return
      rg --colors "match:bg:yellow" --colors "match:fg:magenta" -e 'Ran 0 tests in 0.000s' -e pythonImportTests -e pythonImportCheck -e pythonImportTests &
      for file in *.log; do
        cd ../nixpkgs/
        nixpkgs-hammer "${file%.*}"
        sleep 0.1
      done
    )
    cat report.md
    export NIXPKGS_REVIEW_LINT_RUN=1
  fi
}
```

**Comment by SuperSandro2000** [comment]
Integrated into nixpkgs-review-check though nixpkgs-hammering.
