### ISSUE TITLE
Support for oauth_token from gh client

### ISSUE THREAD

**Issue by hmenke** [Mic92/nixpkgs-review#168]
Currently nixpkgs-review supports reading the oauth_token from either the environment variables `GITHUB_TOKEN` or from an existing [hub](https://github.com/github/hub) configuration file:

https://github.com/Mic92/nixpkgs-review/blob/f731b4df0c2e5fced7b18c2a498dc3fc7c113c61/nixpkgs_review/cli/__init__.py#L111-L137

The [gh](https://github.com/cli/cli) client also stores the oauth_token in a configuration file, namely `~/.config/gh/hosts.yml` which looks like this
```
github.com:
    user: ...
    oauth_token: ...
```
Please support reading the token from this file as well.

**Comment by Mic92** [comment]
Does it quote the string in the file? If not, one could match it in the same way.

**Comment by hmenke** [comment]
The field `oauth_token` is unquoted.  With some imaginary values it looks like this:
```
github.com:
    user: foobar
    oauth_token: 5891b5b522d5df086d0ff0b110fbd9d21bb4fc71
```
