### ISSUE TITLE
Add support for gh in addition to hub for oauth_token

### ISSUE THREAD

**Issue by davidak** [Mic92/nixpkgs-review#180]
>Additionally nixpkgs-review will also read the oauth_token stored by hub.

>GitHub CLI (gh) was announced in early 2020 and provides a more seamless way to interact with your GitHub repositories from the command line

https://cli.github.com/
https://github.com/cli/cli/blob/trunk/docs/gh-vs-hub.md

**Comment by Mic92** [comment]
Implemented in https://github.com/Mic92/nixpkgs-review/issues/168
