### ISSUE TITLE
1 package marked as broken and skipped

### ISSUE THREAD

**Issue by davidak** [Mic92/nixpkgs-review#192]
`nixpkgs-review pr 118921` marked package as broken and skipped, but it shouldn't.

build works with nix-build

@Mic92 do you have an idea why this happens?

https://github.com/NixOS/nixpkgs/pull/118921

**Comment by Mic92** [comment]
Is evaluation in the package maybe broken? ofborg also does not evaluate.

**Comment by SuperSandro2000** [comment]
ofborg-eval is red so this is expected.
