### ISSUE TITLE
Don't require a patch comment when the patch is a local file

### ISSUE THREAD

**Issue by roberth** [Mic92/nixpkgs-review#207]
I would like to avoid a situation where we have nonsense commits and nonsense comments littering Nixpkgs.

We correctly [ask](https://github.com/NixOS/nixpkgs/pull/130091#issuecomment-879101508) for patches to come with a comment because we prefer to fetch them and we have no other place to provide context for the patch. See also https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md

However, when the a patch is a local file, because it is not upstreamable, we have plenty of control and the file name or embedded message can cover all there is to know. See https://github.com/NixOS/nixpkgs/pull/130102#discussion_r669390966

So I suggest we don't report missing comments when the patch is a path expression.

**Comment by Mic92** [comment]
This error comes from nixpkgs-hammering not nixpkgs-review. I don't have control over the message. nixpkgs-review also don't integrate nixpkgs-hammering the bot does.
