### ISSUE TITLE
aarch64-darwin: `pr` fails on unrelated package `live555`

### ISSUE THREAD

**Issue by polynomialspace** [Mic92/nixpkgs-review#213]
Trying to use `pr`, `wip`, or even `rev` on aarch64-darwin fails on this seemingly unrelated package, trying to `-P live555` and/or `-p packageToActuallyBeTested` doesn't seem to affect anything. All leads to an error like the following (picked a random PR here): 
```
[...]
$ nix-env --option system aarch64-darwin -f /Users/ash/.cache/nixpkgs-review/pr-133535/nixpkgs -qaP --xml --out-path --show-trace
error: attribute 'aarch64-darwin' missing

       at /Users/ash/.cache/nixpkgs-review/pr-133581/nixpkgs/pkgs/development/libraries/live555/default.nix:29:22:

           28|
           29|     ./genMakefiles ${{
             |                      ^
           30|       x86_64-darwin = "macosx";

       … while evaluating the attribute 'configurePhase' of the derivation 'live555-2019.11.22'

       at /Users/ash/.cache/nixpkgs-review/pr-133581/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:203:11:

          202|         // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          203|           name =
             |           ^
          204|             let

       … while querying the derivation named 'live555-2019.11.22'
https://github.com/NixOS/nixpkgs/pull/133581 failed to build
```

Using `--system x86_64-darwin` is one workaround but doesn't always work.
```
error: a 'x86_64-darwin' with features {} is required to build '/nix/store/fjdavfgdbrfdmc5p0v5n35bqyrqfkn5r-source.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test, recursive-nix}
```

**Comment by SuperSandro2000** [comment]
I think the code here https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/live555/default.nix#L29-L34 lacks handling for other arches. nixpkgs-review evals all packages once ignoring meta.broken to know which packages are available and the code piece does not work for that. I thought ofborg should catch such issues.

**Comment by SuperSandro2000** [comment]
@polynomialspace Could you locally checkout https://github.com/NixOS/nixpkgs/pull/133732 and do ``nixpkgs-review rev HEAD``? I think that should show us if the fix works and where the next problem is if that attempt is correct.

**Comment by polynomialspace** [comment]
That seems to have done it. Misunderstanding how nixpkgs-review works I thought this was something deeper.
