### ISSUE TITLE
Fails to build on r-ryantm's pull requests with nix-community cachix

### ISSUE THREAD

**Issue by figsoda** [Mic92/nixpkgs-review#221]
```ShellSession
$ nixpkgs-review pr 138440
```

```ShellSession
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/138440/head:refs/nixpkgs-review/1
[...]
$ git worktree add /home/figsoda/.cache/nixpkgs-review/pr-138440/nixpkgs a66236713c63c1928543efa99cb7455ff85aab9b
[...]
$ git merge --no-commit --no-ff 5fc4fdac51a952c03692946d0ba66e7b42b751e9
Automatic merge went well; stopped before committing as requested
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/figsoda/.cache/nixpkgs-review/pr-138440/build.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/138440

2 packages failed to build:
terraform-ls vscode-extensions.hashicorp.terraform

error: build log of '/nix/store/a6k8fwkb5q4ryf7swag9yfq5nkx31l2j-terraform-ls-0.22.0.drv' is not available
error: build log of '/nix/store/aqgivjnkqq33pvp47lhc7mp0w1f55hbs-terraform-ls-0.22.0' is not available
error: build log of '/nix/store/cl94yzjkslph8ggqvahmw0ralp4z4af1-vscode-extension-hashicorp-terraform-2.14.0.drv' is not available
error: build log of '/nix/store/cjnb84n1jz444yvr67x1mc8cdzxsn7x2-vscode-extension-hashicorp-terraform-2.14.0' is not available
$ nix-shell /home/figsoda/.cache/nixpkgs-review/pr-138440/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-138440]$
```

`nixpkgs-review` doesn't build anything and fails immediately on r-ryantm's pull requests, and removing nix-community.cachix.org from caches solves the issue
I don't what is causing this, nixpkgs-review, nixpkgs-update, cachix, or nix

**Comment by Mic92** [comment]
I have seen this too, once I build it inside this nix-review shell it works again. I have not debugged the root cause of it.

**Comment by SuperSandro2000** [comment]
I can confirm that the same happens for me locally.

**Comment by figsoda** [comment]
A temporary solution I can think of is adding a `--option` flag to pass nix options, or having some other flag to pass flags to nix, so I can do something like `--option substituters https://cache.nixos.org/` or `--nix-flags "--option substituters https://cache.nixos.org/"` to disable the nix-community cache temporarily

**Comment by domenkozar** [comment]
> We use the return code of `nix-store --verify-path <store-path>` to check if a package failed. We should first check why it seems to return 1 for cachix fetched packages.

Interesting, I can't find that in the code: https://github.com/Mic92/nixpkgs-review/search?q=verify-path&type=code

**Comment by figsoda** [comment]
> > We use the return code of `nix-store --verify-path <store-path>` to check if a package failed. We should first check why it seems to return 1 for cachix fetched packages.
> 
> Interesting, I can't find that in the code: https://github.com/Mic92/nixpkgs-review/search?q=verify-path&type=code

https://github.com/Mic92/nixpkgs-review/blob/548447c72e8fa761a2b7afce9e663968563826db/nixpkgs_review/nix.py#L33

**Comment by domenkozar** [comment]
I've tried to look into what's wrong here, but nix-review doesn't give enough debugging information.

If someone can boil it down, I'm happy to fix things on Cachix side if need be.

**Comment by SuperSandro2000** [comment]
I think I know what is going on: we are grepping the review shell from the cache without any of it build dependents which means the "build" succeeds but then none of the things we wanted to build are there.
