### ISSUE TITLE
Clean environment inside the nixpkgs-review shell

### ISSUE THREAD

**Issue by thiagokokada** [Mic92/nixpkgs-review#235]
It would be interesting to have an option that creates the shell in `nixpkgs-review pr` without environment variables set and `HOME` pointing to a temporary directory.

This is because I generally test the binaries that I build with `nixpkgs-review`, however some binaries started messing with my `HOME` environment (one bad case was a program that put a script inside my `HOME` directory and with auto start; the script itself seemed inoffensive but this is unacceptable). Nowadays I am adding something like `HOME=$(mktemp -d) <binary-name>`, but if we could have an parameter that does so automatically it would be better.

Better yet would be to have a true sandbox, maybe using something like bubblewrap, but I understand this may go completely outside the idea of the tool.

**Comment by Mic92** [comment]
`nix-shell --pure`

**Comment by thiagokokada** [comment]
For some reason `nix-shell --pure -p nixpkgs` is not unsetting the environment variables (and also my shell is very buggy).

**Comment by thiagokokada** [comment]
I did a wrapper based on [nix-cage](https://github.com/corpix/nix-cage) (actually [my fork](https://github.com/thiagokokada/nix-cage) since the code is old enough to not build with current version of nixpkgs).

https://github.com/thiagokokada/nix-configs/commit/1758dc906d8dd70606d996fe9ab8a6ec14eadfce

I think something similar using `bwrap` should be viable with `nixpkgs-review` itself. If this is acceptable I can try to take a shot at implementing this myself.

**Comment by thiagokokada** [comment]
Improved version: https://github.com/thiagokokada/nix-configs/blob/master/packages/nixpkgs-review-cage/nixpkgs-review-cage.sh

**Comment by Mic92** [comment]
Nice! If you have some provide something that explains how to install this script, I would link from nixpkgs-review to it.

**Comment by thiagokokada** [comment]
> Nice! If you have some provide something that explains how to install this script, I would link from nixpkgs-review to it.

I am thinking of contributing a similar functionality to `nixpkgs-review` itself. I took a look at the code yesterday and it seems relatively easy.

WDYT @Mic92? Would this be an acceptable feature to have on `nixpkgs-review`? I am thinking of having this feature behind a `--sandbox` or some other parameter.

**Comment by Mic92** [comment]
I am ok, if bubblewrap stays an optional runtime dependency (not in closure of nixpkgs-review). I would also prefer if the implementation uses bubblewrap directly rather than a shell wrapper.
