### ISSUE TITLE
Can't build current commit on master

### ISSUE THREAD

**Issue by thiagokokada** [Mic92/nixpkgs-review#240]
Having the following error while using `nix build`:

http://ix.io/3Ij2

Reverting commit 107cb2285f10a0a5daddd4995516efede96bdbe3 works fine.

**Comment by thiagokokada** [comment]
I think the issue is that the current `flake.lock` is too old. Updating `nixpkgs` seems to work fine.

**Comment by Mic92** [comment]
fixed in https://github.com/Mic92/nixpkgs-review/pull/241
