### ISSUE TITLE
Don't merge/rebase

### ISSUE THREAD

**Issue by piegamesde** [Mic92/nixpkgs-review#250]
I often use `nixpkgs-review` during the development of a PR. In this, the feature that the PR is rebased or merged onto master is rather annoying:

- It takes quite a lot of time, although iteration time is important to me
- It makes things harder to develop, as master is a moving target (new error may appear over time, and results between review and my local checkout may differ)
- It totally breaks when there are any merge conflicts. This is especially annoying since our new (21.11) release notes policy

Please add a flag so that I can skip that check and only build the packages as they are in the code.

**Comment by SuperSandro2000** [comment]
You want to use ``nixpkgs-review rev``, ``nixpkgs-review pr --checkout commit`` or ``nixpkgs-review wip``.
