### ISSUE TITLE
Not correctly calculating dependent packages to be built

### ISSUE THREAD

**Issue by Binary-Eater** [Mic92/nixpkgs-review#253]
Noticing that zero packages are being built for [NixOS/nixpkgs#157475](https://github.com/NixOS/nixpkgs/pull/157475) in comparison to [NixOS/nixpkgs#156203](https://github.com/NixOS/nixpkgs/pull/156203). Is this because of the defaulting of the `stable` derivation in [nixpkgs/nixos/modules/hardware/video/nvidia.nix](https://github.com/NixOS/nixpkgs/blob/dad4fddd52923d90c5ad981d5e29963e829de3c1/nixos/modules/hardware/video/nvidia.nix#L167), which is unchanged in the review failing to build the dependent packages? The PR in question only changes the `legacy_340` derivation.

**Comment by Mic92** [comment]
You are only removing packages from the looks of it, by marking them as broken: https://github.com/NixOS/nixpkgs/pull/157475/files#diff-eaaf2ab625a2242deeeec90b489435aad3c0d33bbfc3be578a2fa20b0b6d044eR80
Hence there are no package rebuilds.

**Comment by Binary-Eater** [comment]
I guess it would be nice when just removing packages for the results to be populated with at least a new list of packages marked explicitly broken (to post in the review), but I agree on the fact that just removing packages should warrant no building. Right now, the results files look like the following (which is expected behavior I presume as of today).

###### results.json

```
{
    "blacklisted": [],
    "broken": [],
    "built": [],
    "failed": [],
    "non-existant": [],
    "pr": 157475,
    "system": "x86_64-linux",
    "tests": []
}
```

###### results.md

```
Result of `nixpkgs-review pr 157475` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
```

**Comment by Mic92** [comment]
I am not sure they are even marked as broken for kernel packages. It's just like python packages not being build for certain python versions.

**Comment by Mic92** [comment]
Since ofborg is not giving us this information, I also don't see a cheap way to implement it.

**Comment by Binary-Eater** [comment]
> I am not sure they are even marked as broken for kernel packages. It's just like python packages not being build for certain python versions.

I think they are based on this, or I probably am misunderstanding something.

https://github.com/NixOS/nixpkgs/pull/156203#issuecomment-1019607830

**Comment by SuperSandro2000** [comment]
The PR you linked caused rebuilds which ofborg reports and added labels according to that. When marking packages as broken only the metadata is changing and they are no longer build, not rebuild.
