### ISSUE TITLE
Add shell completion

### ISSUE THREAD

**Issue by JamieMagee** [Mic92/nixpkgs-review#294]
It would be nice to have shell completion (tab completion/autocompletion/whatever you want to call it)

**Comment by Mic92** [comment]
For zsh someone wrote it: https://github.com/spwhitt/nix-zsh-completions
Whats the best way to autogenerate this for python's argumentparser?

**Comment by JamieMagee** [comment]
The solution appears to be [argcomplete][1].

[1]: https://kislyuk.github.io/argcomplete/

**Comment by Mic92** [comment]
I would accept a PR that adds a script to generate the completion script so that we can check it into the git repo.
