### ISSUE TITLE
Printing the result comment to stdout instead of posting it

### ISSUE THREAD

**Issue by ruuda** [Mic92/nixpkgs-review#311]
There is `nixpkgs-review post-result`, but it requires a GitHub access token, and I’m not really comfortable giving `nixpkgs-review` access to one. If `nixpkgs-review` could print the comment that it would post, I would happily paste it into the comment box in my browser and post it manually.

**Comment by figsoda** [comment]
The results are stored in `report.md` if that helps, but it does make some sense to have ` print-result` command and `--print-result` flag

**Comment by Mic92** [comment]
I think we would only need `--print-result-md` flag as we the other command could be also just `cat report.md` instead.

**Comment by figsoda** [comment]
opened #312 to implement `--print-result`, I named it without  `-md` to be more consistent with `--post-result`
