### ISSUE TITLE
Allow passing extra arguments to `import <nixpkgs>`

### ISSUE THREAD

**Issue by SomeoneSerge** [Mic92/nixpkgs-review#314]
Use-case: running `nixpkgs-review` with `config.cudaSupport = true` and custom `config.cudaCapabilities`.
Currently, `nixpkgs-review` only tracks affected cuda-enabled packages if they expose a `xxxWithCuda` attribute in nixpkgs.
Not all packages do that, and it's debatable whether they should.

I think a satisfiable solution would be e.g. being able to run `nixpkgs-review pr XXXXXX --extra-nixpkgs-config '{ config.cudaSupport = true; }'`. I imagine `nixpkgs-review` could explicitly state any extra options it has received in the report that it publishes as a github comment, since these options could (and do) affect the eval

**Comment by figsoda** [comment]
#315

**Comment by SomeoneSerge** [comment]
Thank you @figsoda!
