### ISSUE TITLE
display packages marked as broken

### ISSUE THREAD

**Issue by teto** [Mic92/nixpkgs-review#329]
Is it possible to ignore/display differently packages marked as broken ? 

I run nixpkgs-review on https://github.com/NixOS/nixpkgs/pull/224553 where I mark a certain number as broken so I know they dont build. But because there are so many builds, having these packages appear in the nixpkgs-review report is annoying.

Ideally we would have  https://github.com/Mic92/nixpkgs-review/issues/141 too to show "newly broken" vs ""already broken" but that's a different feature.

**Comment by figsoda** [comment]
I think it was broken in #315, sorry about that

I will push a fix soon

**Comment by figsoda** [comment]
could you test if #330 fixes the issue for you?

**Comment by teto** [comment]
ty that fixed it.
