### ISSUE TITLE
Fails to run in pure evaluation mode

### ISSUE THREAD

**Issue by soispha** [Mic92/nixpkgs-review#355]
# How to reproduce
1. Add  `nix.pure-eval = true` to your nixos-config (or add `pure-eval = true` in nix.conf).
2. Every try to run `nixpkgs-review` will now fail, as access to the nixpath (`<nixpkgs>`) is forbidden.

# Possible fixes
 - Either add `--impure` to every `nix` invocation that tries to access `<nixpkgs>` or
 - Remove the need to import `<nixpkgs>` in the first place.

Implementing the second idea would probably necessitate adding a hash backed `builtins.fetchTarball` call, or something like it, to get access to nixpkgs.

**Comment by Mic92** [comment]
I don't think you can have this set globally and still expects all tools to work properly. This should be only set on a cli level.

**Comment by Mic92** [comment]
We are already passing --impure to nix.

**Comment by Mic92** [comment]
I don't want to also add workarounds for this configuration. This would also break normal nix-shell usage and co. Don't do it or live with the consequences.
