### ISSUE TITLE
Just get failed to build

### ISSUE THREAD

**Issue by dani0854** [Mic92/nixpkgs-review#361]
I am just getting failed to build error.

I have added a package, and `nix build` and tests work fine. But when I run `nixpkgs-review pr`, I just get "failed to build", with no additional context.

Where can I find extended logs, or something simmilar.

Logs:
```
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/255080/head:refs/nixpkgs-review/1
$ git worktree add /home/dsuetin/.cache/nixpkgs-review/pr-255080-4/nixpkgs 11419311288d6b186e96b55b682cd9d4f2ff20a8
Preparing worktree (detached HEAD 11419311288d)
Updating files: 100% (37177/37177), done.
HEAD is now at 11419311288d Merge pull request #255027 from JerrySM64/update-linux-zen
$ nix-env --extra-experimental-features no-url-literals --option system x86_64-linux -f <nixpkgs> --nix-path nixpkgs=/home/dsuetin/.cache/nixpkgs-review/pr-255080-4/nixpkgs nixpkgs-overlays=/tmp/tmp9aoe2wks -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
https://github.com/NixOS/nixpkgs/pull/255080 failed to build
$ git worktree remove -f /home/dsuetin/.cache/nixpkgs-review/pr-255080-4/nixpkgs
```

**Comment by Mic92** [comment]
Did you run out-of-memory evaluating nixpkgs?

**Comment by Mic92** [comment]
Is the error still reproducible on the repository after ofborg has evaluated the pull request?

**Comment by dani0854** [comment]
I don't think I ran out of memory.
But the error seems to go away now.

Before it was reproducible, I tried building about 5 times. Can't reproduce now.

**Comment by Mic92** [comment]
It's not really clear to me what the problem is, but I refactored nixpkgs-review to print the underlying error better: https://github.com/Mic92/nixpkgs-review/pull/362

**Comment by dani0854** [comment]
Thanks, if I get the same error again I will hope it will have more context, and might open a different issue. Closing this one for now.

**Comment by Mic92** [comment]
https://github.com/Mic92/nixpkgs-review/releases/tag/2.10.2
