### ISSUE TITLE
`--skip-package-regex` and `--skip-package-regex` do not work in `rev` mode

### ISSUE THREAD

**Issue by Atemu** [Mic92/nixpkgs-review#363]
Trying to review a huge staging PR, I used  `--skip-package-regex` to skip over a few packages that I know wouldn't be broken or that I don't want to build this worked in pr mode. Cloning the PR and trying to run `nixpkgs-review rev HEAD -b ... --skip-package-regex ...` does not actually skip package names that match the regex which is extremely confusing.

`nixpkgs-review` should either support `--skip-package` in `rev` mode or error out, rather than silently ignoring the flag.

An easy way to repro this is to create a commit touching `hello` in some way (i.e. breaking it) and then running with `--skip-package hello`. It should not build anything but in actuality it tries to build hello.

**Comment by Mic92** [comment]
fixed in https://github.com/Mic92/nixpkgs-review/pull/364
