### ISSUE TITLE
Failure to find remote ref for a specific PR

### ISSUE THREAD

**Issue by athre0z** [Mic92/nixpkgs-review#367]
When running nixpkgs-review on [this particular PR](https://github.com/NixOS/nixpkgs/pull/260719):

```
nixpkgs-review pr 260719
```

I'm running into the following error:

```
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/260719/head:refs/nixpkgs-review/1
fatal: couldn't find remote ref pull/260719/head
https://github.com/NixOS/nixpkgs/pull/260719 failed to build: Failed to fetch ('master', 'pull/260719/head') from https://github.com/NixOS/nixpkgs. git fetch failed with exit code 128
$ git worktree remove -f /home/ath/.cache/nixpkgs-review/pr-260719/nixpkgs
fatal: '/home/ath/.cache/nixpkgs-review/pr-260719/nixpkgs' is not a working tree
Failed to remove worktree at /home/ath/.cache/nixpkgs-review/pr-260719/nixpkgs. Please remove it manually. Git failed with: 128
```

The important bit seems to be:

```
fatal: couldn't find remote ref pull/260719/head
```

Other PRs, also those created later, work just fine. I don't see anything particularly special about that PR. I already tried nuking my `nixpkgs` and re-cloned it, but it didn't change anything.

Any idea what could cause this? Some GitHub bug where this ref wasn't created?

**Comment by Mic92** [comment]
Looks like a github bug to me. I don't think there is anything I can fix in nixpkgs-review to counter that.

**Comment by athre0z** [comment]
Alright, thanks! I'll close this for the moment then & we can revisit / report this to GH if it happens again.
