### ISSUE TITLE
how to just list the affected packages without building them ?

### ISSUE THREAD

**Issue by teto** [Mic92/nixpkgs-review#376]
silly question maybe but couldn't find the solution. 
I have changed a package in my local nixpkgs and I would like to know how many packages it impacts (ie. number of package that will need rebuilding) out of curiosity (and also to decide which merge branch to target). Usually I rely on ofborg but it's pretty slow lately. 

Is there a way to run nixpkgs-review to just list the impacted packages without rebuildings them ? or another script/solution/ like a public ofborg script I could run locally ?

**Comment by Artturin** [comment]
There is `./maintainers/scripts/rebuild-amount.sh`  in nixpkgs

**Comment by teto** [comment]
amazing, I've been contributing for years without knowing about this ^^'' . Thanks a lot
