### ISSUE TITLE
nixpkgs-review shell breaks pr 277935

### ISSUE THREAD

**Issue by quantenzitrone** [Mic92/nixpkgs-review#383]
https://github.com/NixOS/nixpkgs/pull/277935
I don't really know what is going on and it is probably also not nixpkgs-review fault, but:
this crashes:
```sh
nixpkgs-review pr 277935
gprename
```

and these all do not:
```sh
nixpkgs-review pr 277935 --sandbox
gprename
```
```sh
nix build github:quantenzitrone/nixpkgs/gprename#gprename
result/bin/gprename
```
```sh
nix build github:quantenzitrone/nixpkgs/gprename#gprename
env --ignore-environment DISPLAY=$DISPLAY HOME=$HOME result/bin/gprename
```

so there must be something in the non-sandboxed nixpkgs-review shell that crashes gprename...

**Comment by SuperSandro2000** [comment]
Can you start the program with strace?

**Comment by quantenzitrone** [comment]
I found out the deciding factor: the folder. In `~/.cache/nixpkgs-review/pr-*` it crashes, anywhere else not.
The strace output is huge and basically dumps my whole home folder structure into stderr.
I don't want to post this publicly on GitHub, I could send it to you privately if you want.

**Comment by quantenzitrone** [comment]
https://sourceforge.net/p/gprename/bugs/28/
