### ISSUE TITLE
Pass/fail reports are not visually distinct enough to tell apart at a glance

### ISSUE THREAD

**Issue by Atemu** [Mic92/nixpkgs-review#404]
In https://github.com/NixOS/nixpkgs/pull/318912 @siraben posted a nixpkgs-review but nobody noticed that the nixpkgs-review text said that the build has *failed*. Luckily, it was just a fluke but this shouldn't happen. A failure should be obvious and not easily confused with a pass.

To improve nixpkgs-review in this regard, I propose usage of obviously distinct visual patterns for pass and failed such as emboldening **failed** or adding an emoji.

I don't typically use them but I think Emoji could really shine here as they feature bright obvious colours and distinct shapes.

Does that sound good?

**Comment by Mic92** [comment]
Sure. Let's add some :fire:
