### ISSUE TITLE
Insight on why shell-review attempts to parse a hosts file as a script

### ISSUE THREAD

**Issue by Frontear** [Mic92/nixpkgs-review#407]
Hi!

Got a PR on nixpkgs [here](https://github.com/NixOS/nixpkgs/issues/321649) with a variety of improvements for the stevenblack-blocklist package + nixos modules, and I'm running into a very odd error when running the standard review from HEAD.

```
┃ error: builder for '/nix/store/dmr7w0cqxdj0xbz1l5fm5wm124c2jc09-review-shell.drv' failed with exit code 127;
┃        last 3 log lines:
┃        > /nix/store/1jik86ikk79rlkhrnwmyksfzcnhgaa6l-stevenblack-blocklist-3.14.84-ads: line 15: 127.0.0.1: command not found
┃        > /nix/store/d3dzfy4amjl826fb8j00qp1d9887h7hm-stdenv-linux/setup: line 692: pop_var_context: head of shell_variables not a function context
┃        > /nix/store/d3dzfy4amjl826fb8j00qp1d9887h7hm-stdenv-linux/setup: line 699: pop_var_context: head of shell_variables not a function context
┃        For full logs, run 'nix log /nix/store/dmr7w0cqxdj0xbz1l5fm5wm124c2jc09-review-shell.drv'.
```

I was hoping for some insight regarding why this error seems to happen. It looks like its trying to process the hosts file as a shell script, and failing on the first line that declares localhost bindings.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/blob/4cccdeaffb6f676b44e58ff7ef37415239ec863b/pkgs/stdenv/generic/setup.sh#L647

the line was added in https://github.com/nixos/nixpkgs/commit/b23dbb1a5dffbfa3abb47fcd0f1579ac2e6f29fc

**Comment by Frontear** [comment]
What should I consider this, a bug in nixpkgs-review or a mistake in my approach? I mean ultimately its not causing any real issues, my PR is completely fine and will merge correctly, but I wonder if its something worth changing either here or there.

**Comment by Frontear** [comment]
Oh yes my mistake, nixpkgs not this. I think I'll end up changing my outputs and then subsequently maybe raising this as a separate issue upstream.
