### ISSUE TITLE
Running `nixpkgs-review pr 337953` takes indefinitely long

### ISSUE THREAD

**Issue by rrcomtech** [Mic92/nixpkgs-review#413]
I'm running 

```
nixpkgs-review pr 337953
```

and get 

```
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/337953/head:refs/nixpkgs-review/1
```

After that, nothing happens. I assume that this is due to the size of nixpkgs. So is there a way I can still use `nixpkgs-review`?

**Comment by rrcomtech** [comment]
Yes, `git fetch` works just fine and completes within a couple of seconds. What are the requirements on the nixpkgs dir that I'm in? I don't have a complete clone of the nixpkgs repo, but a repo containing only the branch that I want to review.

**Comment by Mic92** [comment]
Ah. maybe git doesn't find the matching ref and does some really slow search. I think it's better to have the full history.

**Comment by rrcomtech** [comment]
But cloning the full master might be really hard to do? Even the wiki suggests running `git clone <nixpkgs> --depth 1`. So you wouldn't have the whole history. At least cloning on my machine fails when not specifying `--depth 1`.

**Comment by Mic92** [comment]
Not sure how to fix this. Not sure why you cannot just do a full clone of nixpkgs.

**Comment by rrcomtech** [comment]
Usually, cloning such a big project does not work well on smaller machines. I guess I got it working now, when using a bigger internet connection.
