### ISSUE TITLE
Don't evaluate nixpkgs if `--package` was passed

### ISSUE THREAD

**Issue by PerchunPak** [Mic92/nixpkgs-review#430]
This makes `--package` almost useless. I would want to build all packages by regex without waiting for 30m evaluation that won't produce any useful information for me.

I tried to create a script that builds packages by regexes, but turns out it is not so simple to filter out broken/unbuildable by architecture packages (or at least don't cancel build because of them).

**Comment by Mic92** [comment]
Now that we are able to use nixpkgs evaluation results that come in faster, we should be able to skip evaluation in most cases.

**Comment by PerchunPak** [comment]
I ended up creating such script, but it can build only by namespace. It's not a three liner at all

https://gist.github.com/PerchunPak/38651e3bac112504eb69caa33eb18c3a

**Comment by Mic92** [comment]
Sounds good.
