### ISSUE TITLE
Build failing attributes on master to determine if cause is due to changes

### ISSUE THREAD

**Issue by Pandapip1** [Mic92/nixpkgs-review#431]
When a PR that changes a commonly-used dependency is opened, there are frequently failing packages that also fail on master and aren't marked as broken (e.g. https://github.com/NixOS/nixpkgs/pull/355478#issuecomment-2485455483). `nixpkgs-review` should try building the failing packages on master to determine if they are broken (but not marked as such) or if the PR really does break them.

**Comment by Mic92** [comment]
Borrowing code from https://github.com/nix-community/hydra-check might help.

**Comment by Pandapip1** [comment]
Well, assuming the packages are building successfully, they'll probably be cached in the binary cache.

**Comment by Mic92** [comment]
closing because of duplicate.

**Comment by Mic92** [comment]
> Well, assuming the packages are building successfully, they'll probably be cached in the binary cache.

Very often not the case on master.
