### ISSUE TITLE
GHA eval support

### ISSUE THREAD

**Issue by wegank** [Mic92/nixpkgs-review#433]
Since https://github.com/NixOS/nixpkgs/pull/359704, there is an evaluation output available as an artifact in the `Eval / Process (pull_request_target)` check. It would be nice to reuse it to skip local evaluation.

**Comment by Mic92** [comment]
@GaetanLepage is working on this.

**Comment by GaetanLepage** [comment]
Yes, I have started to look at it and will work on it this WE.

**Comment by getchoo** [comment]
Is `./ci/eval` faster than the current method used for local eval? Could be nice for running `nixpkgs-review rev HEAD` before pushing

**Comment by GaetanLepage** [comment]
> Is `./ci/eval` faster than the current method used for local eval? Could be nice for running `nixpkgs-review rev HEAD` before pushing

Well, there are two things that I want to add to `nixpkgs-review`:
1. Retrieving the eval results from the GHA (when available) to prevent doing any work locally.
2. Use the new eval code in `ci/eval` to perform multi-threaded evaluation locally.
