### ISSUE TITLE
Can this be used on forks of nixpkgs?

### ISSUE THREAD

**Issue by CMCDragonkai** [Mic92/nixpkgs-review#44]
Or other kinds of nixpkgs repositories like private nixpkgs repos.

**Comment by Mic92** [comment]
In theory yes. In practice nixpkgs is hard-coded at the moment:
https://github.com/Mic92/nix-review/blob/master/nix_review/review.py#L209

**Comment by Mic92** [comment]
This was implemented in https://github.com/Mic92/nixpkgs-review/pull/69
