### ISSUE TITLE
Python2 and Python3 mixed during review

### ISSUE THREAD

**Issue by danbst** [Mic92/nixpkgs-review#46]
Noticed this on `nix-review pr 53537`:
```
{ pkgs ? import ./nixpkgs {} }:
with pkgs;
stdenv.mkDerivation {
  name = "env";
  buildInputs = [
    check-esxi-hardware
    cloud-init
    cloud-utils
    crda
    euca2ools
    hash-slinger
    python27Packages.m2crypto  # <-- python2
    python27Packages.osc
    python27Packages.pywbem
    python37Packages.m2crypto  # <-- python3
    tribler
    virtinst
  ];
  unpackPhase = ":";
  installPhase = "touch $out";
}
```
This caused bad errors.

**Comment by Mic92** [comment]
Sorry, but I have no clue how this could be solved in a meaningful way, other then manually invoking `PYTHONPATH= nix-shell -p  python27Packages.m2crypto` within the review shell.

**Comment by Mic92** [comment]
This problem might solve its self with the deprecation of python27.

**Comment by Mic92** [comment]
closing this for now. I don't how to fix this, but I also think it won't be relevant at some point.
