### ISSUE TITLE
Specify cache directory for temporary worktree

### ISSUE THREAD

**Issue by timor** [Mic92/nixpkgs-review#58]
It would be good if it was possible to specify an alternate temporary directory than `$HOME/.cache` for the git work tree.

I tried setting  `XDG_CACHE_HOME` explicitely when running `nix-review` but as far as I can tell , that has no effect if  `HOME` is set.

**Comment by Mic92** [comment]
Should be fixed by: https://github.com/Mic92/nix-review/pull/59
