### ISSUE TITLE
Feature request: attempt to rebuild failing packages using PR-base tree

### ISSUE THREAD

**Issue by risicle** [Mic92/nixpkgs-review#71]
Something I often find myself doing is trying to determine whether a build failure was _caused by_ the PR or whether a particular package was already failing on my machine anyway. Currently it's a little painful fetching & checking out the branch's base, could be made a lot quicker...

**Comment by timokau** [comment]
I think this is a duplicate of https://github.com/Mic92/nixpkgs-review/issues/85. Although this issue was created earlier, #85 has already seen some discussion so this should probably be closed.

**Comment by risicle** [comment]
I concur.

**Comment by jonringer** [comment]
sorry about the duplicate. I guess I was specifically looking for the term regression or diff
