### ISSUE TITLE
Feature request: Let me use the relaxed sandbox

### ISSUE THREAD

**Issue by lilyball** [Mic92/nixpkgs-review#75]
`nix-review` enables the sandbox always, but sometimes on darwin we need to use the `relaxed` option instead (in particular, if the derivation specifies a custom sandbox profile). For example, I can't use `nix-review` to build `nixpkgs.macvim` because that requires `relaxed` mode. To that end, I'd really like a flag that controls the sandbox option. This could also solve #55, if I can just provide a free-form value that's used instead of `true` for the sandbox option.

**Comment by Mic92** [comment]
How would the concrete option would look like?

**Comment by lilyball** [comment]
My recommendation is just a `--sandbox <VALUE>` option, available on all 3 subcommands, where `<VALUE>` is `true`, `false`, or `relaxed`.
