### ISSUE TITLE
Set max-jobs option to nix build

### ISSUE THREAD

**Issue by jonringer** [Mic92/nixpkgs-review#78]
I got a 3900X, and having 24 jobs take up potentially 24 cores each actually hinders the job (as well as makes my computer almost unusable). Would really like to have an option where I can do something like `NIX_REVIEW_MAX_JOBS=4 nix-review pr <...>`, using an env var also makes the implementation easier:

```
# nix.py
...
        os.environ.get("NIX_REVIEW_MAX_JOBS", str(multiprocessing.cpu_count())),
...
```

**Comment by Mic92** [comment]
Maybe this should not be set at all.

**Comment by jonringer** [comment]
also acceptable :)

**Comment by samuela** [comment]
How does one go about setting `max-jobs` when using nixpkgs-review?

**Comment by Mic92** [comment]
Try the  `--build-args` option.
