### ISSUE TITLE
Mention removed packages

### ISSUE THREAD

**Issue by teto** [Mic92/nixpkgs-review#87]
I've run nixpkgs-review on https://github.com/NixOS/nixpkgs/pull/81173. The result is a 'Nothing changed' while the PR removes 2 packages. I would like to see the attributes removed if possible ?

**Comment by Mic92** [comment]
This is not possible when using ofborg's evaluation output. However when evaluating locally removed packages are printed: https://github.com/Mic92/nixpkgs-review/commit/e704d6a5b694f79881247f4f39aee12d63bd6575#diff-f40fbcc338878e648a41795e2229bb93R74

You can use `--eval local` to enable it, in which case `nixpkgs-review` will take longer.

**Comment by Mic92** [comment]
There is nothing I can do right now to fix this at the moment.
