### ISSUE TITLE
nixpkgs-review pr <num> --post-result --approve --merge flags

### ISSUE THREAD

**Issue by bhipple** [Mic92/nixpkgs-review#89]
Often, code reviewers will run `nixpkgs-review pr <num>` then manually paste the
results into the code review, like this:

https://github.com/NixOS/nixpkgs/pull/83695

I would like to add the ability to provide a `nixpkgs-review pr 1234 --comment` flag which will do this automatically, using the markdown report that `nixpkgs-review` is already producing.

**Comment by Mic92** [comment]
Sounds good to me.

**Comment by FRidh** [comment]
Maybe call it `--post-result` instead of `--comment`. When I saw `--comment` I had at least the impression I could add additional text. Note that I don't really mind.

**Comment by bhipple** [comment]
Having a `--comment` that lets you add additional text seems like a nice idea, actually.  Something like this is where I'd like to get eventually:

```bash
nixpkgs-review pr 1234 --no-shell --post-result --approve --merge --comment "LGTM, thanks for the contribution!"
```

[I basically have this already](https://github.com/bhipple/dotfiles/blob/master/bin/borg), and @jonringer and I have been using it on PRs for the past week or so and love it, so I'm looking to upstream the features into `nixpkgs-review` for wider consumption.

**Comment by jonringer** [comment]
I agree with @FRidh , I thought it would take another argument as well, allowing for something like `--comment "LGTM\nhas tests :+1:". --post-result is more explicit.

**Comment by Mic92** [comment]
This is now available in NUR as a preview: `nur.repos.mic92.nixpkgs-review-unstable`

**Comment by Mic92** [comment]
This is now released: https://github.com/Mic92/nixpkgs-review/tree/2.3.0

**Comment by NickHu** [comment]
Sorry for flogging a dead horse, but is there a way to do attach a comment to `nixpkgs-review post-result` as @jonringer suggested in his last comment? I saw something like that in one of the PRs he merged, but I wasn't able to figure out how to do it from the `--help` pages.

**Comment by Mic92** [comment]
No. Not at the moment, but it is not hard to add it.
