### ISSUE TITLE
report.md formatting in GitHub email is off

### ISSUE THREAD

**Issue by ryantm** [Mic92/nixpkgs-review#95]
The nixpkgs-review report.md file, when used in nixpkgs-update doesn't look good in email messages:

GitHub PR:
https://github.com/NixOS/nixpkgs/pull/85305

Email screenshot from Gmail:
![image](https://user-images.githubusercontent.com/4804/79355964-3637ca00-7ef3-11ea-9b26-e3301e774e8b.png)

Original email HTML:
```
<p>Result of <code>nixpkgs-review</code> <a href="https://github.com/Mic92/nixpkgs-review">1</a></p>
<details>
  <summary>1 package failed to build:</summary>
<br>- python37Packages.rl-coach
</details>
<details>
  <summary>16 packages built:</summary>
<br>- cmake-format
<br>- patroni
<br>- python27Packages.autopep8
<br>- python27Packages.pyls-isort
<br>- python27Packages.python-language-server
<br>- python37Packages.autopep8
<br>- python37Packages.django_silk
<br>- python37Packages.kubernetes
<br>- python37Packages.pyls-black
<br>- python37Packages.pyls-isort
<br>- python37Packages.pyls-mypy
<br>- python37Packages.python-language-server
<br>- spyder (python37Packages.spyder)
<br>- python38Packages.autopep8
<br>- python38Packages.django_silk
<br>- python38Packages.kubernetes
</details>
```

PR report source:
```
Result of `nixpkgs-review` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
<br>- python37Packages.rl-coach
</details>
<details>
  <summary>16 packages built:</summary>
<br>- cmake-format
<br>- patroni
<br>- python27Packages.autopep8
<br>- python27Packages.pyls-isort
<br>- python27Packages.python-language-server
<br>- python37Packages.autopep8
<br>- python37Packages.django_silk
<br>- python37Packages.kubernetes
<br>- python37Packages.pyls-black
<br>- python37Packages.pyls-isort
<br>- python37Packages.pyls-mypy
<br>- python37Packages.python-language-server
<br>- spyder (python37Packages.spyder)
<br>- python38Packages.autopep8
<br>- python38Packages.django_silk
<br>- python38Packages.kubernetes
</details>
```

cc @bhipple

**Comment by ryantm** [comment]
I think this can probably be fixed by adding <br> or at least a empty line between the detail sections.

**Comment by ryantm** [comment]
Testing:

Result of `nixpkgs-review` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
<br>- python37Packages.rl-coach
</details>

<details>
  <summary>16 packages built:</summary>
<br>- cmake-format
<br>- patroni
<br>- python27Packages.autopep8
<br>- python27Packages.pyls-isort
<br>- python27Packages.python-language-server
<br>- python37Packages.autopep8
<br>- python37Packages.django_silk
<br>- python37Packages.kubernetes
<br>- python37Packages.pyls-black
<br>- python37Packages.pyls-isort
<br>- python37Packages.pyls-mypy
<br>- python37Packages.python-language-server
<br>- spyder (python37Packages.spyder)
<br>- python38Packages.autopep8
<br>- python38Packages.django_silk
<br>- python38Packages.kubernetes
</details>

**Comment by ryantm** [comment]
Testing again:

Result of `nixpkgs-review` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
<br>- python37Packages.rl-coach
</details>


<details>
  <summary>16 packages built:</summary>
<br>- cmake-format
<br>- patroni
<br>- python27Packages.autopep8
<br>- python27Packages.pyls-isort
<br>- python27Packages.python-language-server
<br>- python37Packages.autopep8
<br>- python37Packages.django_silk
<br>- python37Packages.kubernetes
<br>- python37Packages.pyls-black
<br>- python37Packages.pyls-isort
<br>- python37Packages.pyls-mypy
<br>- python37Packages.python-language-server
<br>- spyder (python37Packages.spyder)
<br>- python38Packages.autopep8
<br>- python38Packages.django_silk
<br>- python38Packages.kubernetes
</details>



----


Result of `nixpkgs-review` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
<br>- python37Packages.rl-coach
</details>
<br>
<details>
  <summary>16 packages built:</summary>
<br>- cmake-format
<br>- patroni
<br>- python27Packages.autopep8
<br>- python27Packages.pyls-isort
<br>- python27Packages.python-language-server
<br>- python37Packages.autopep8
<br>- python37Packages.django_silk
<br>- python37Packages.kubernetes
<br>- python37Packages.pyls-black
<br>- python37Packages.pyls-isort
<br>- python37Packages.pyls-mypy
<br>- python37Packages.python-language-server
<br>- spyder (python37Packages.spyder)
<br>- python38Packages.autopep8
<br>- python38Packages.django_silk
<br>- python38Packages.kubernetes
</details>

**Comment by Mic92** [comment]
Did adding spaces work?

**Comment by ryantm** [comment]
The only test that looked good on email looked bad on the website. More testing is needed.

**Comment by Mic92** [comment]
Is this solved by https://github.com/Mic92/nixpkgs-review/pull/118 ?

**Comment by SuperSandro2000** [comment]
Testing

Result of `nixpkgs-review pr 110941` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fluxcd</li>
  </ul>
</details>

**Comment by Mic92** [comment]
I disabled mail notification unfortunately.

**Comment by SuperSandro2000** [comment]
I didn't receive one for my comment...

**Comment by Mic92** [comment]
How about this one? 

Testing

Result of `nixpkgs-review pr 110941` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fluxcd</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
LGTM

![Screenshot_20210222-143011](https://user-images.githubusercontent.com/7258858/108715005-8ff91f80-751a-11eb-8f58-b9178336c7db.jpg)

**Comment by ryantm** [comment]
Yeah those look good but we should also test one with build failures and successes.

**Comment by Mic92** [comment]
Should be the same bullet points for failed builds.
