### ISSUE TITLE
NameError: free variable 'pkg' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by vbgl** [Mic92/nixpkgs-review#99]
Running `nixpkgs-review` crashes when there are some removed packages but no changed ones.

That line seems wrong: https://github.com/Mic92/nixpkgs-review/blob/master/nixpkgs_review/review.py#L70

Possible patch: `s/pkg/p/`.

Scoping rules of python are surprising, to say the least.

**Comment by Mic92** [comment]
Please test and I file a patch release.

**Comment by vbgl** [comment]
Thanks for the quick fix. I’ve just tested it with success on the use-case that used to trigger this error.

**Comment by Mic92** [comment]
https://github.com/Mic92/nixpkgs-review/releases/tag/2.3.1
